import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "FedAI",
  description: "Generated by Machatian Public School",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
